# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Load the default .profile
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

# Make utilities available
PATH="$HOME/bin:$PATH"

# Source sh files in .alias directory
for a in $(ls ${HOME}/.alias/*.sh); do
  . ${a}
done

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
