name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
          
      - name: Setup cookstyle
        run: gem install cookstyle
        
      - name: Run cookstyle
        run: cookstyle cookbooks/jarbas

  Duplicate-analysis:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
          
      - name: Setup cookstyle
        run: gem install flay
        
      - name: Run flay
        run: flay cookbooks/jarbas/*.rb
